# Generated by Django 6.0.3 on 2026-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('CRITICAL', 'CRITICAL')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_high_velocity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='moved_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='movement_trend',
            field=models.CharField(default='+0%', max_length=10),
        ),
    ]
